# ~/.config/fuzzel/fuzzel_theme.ini
# Tone: Rose Pine Duotone (Hồng - Tím nhạt)

[colors]
# Nền launcher (Base Rose Pine) - чуть trong suốt để hòa với wallpaper
background=191724ee

# Màu chữ mặc định (Text - Trắng ngả tím nhẹ)
foreground=e0def4ff

# Màu của các ký tự khớp với từ khóa gõ (Rose - Hồng nhạt)
match=ebbcbaff

# Màu nền của dòng đang được chọn (Overlay - Xám tím đậm hơn nền)
selection=26233aff

# Màu chữ của dòng đang được chọn (Love - Hồng đậm)
selection-text=eb6f92ff

# Màu của ký tự match ở dòng đang được chọn (Gold - Vàng camel tạo điểm nhấn nghệ)
selection-match=f6c177ff

# Màu viền khít với width=8 của bạn tạo khung viền dày
border=26233aff

# Màu của dấu prompt ">> " (Subtle - Xám tím mờ)
placeholder=908caaff
